import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar.js"
import Footer from "./components/Footer.js"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600","700", "800"],
  variable: "--font-poppins",
});


export const metadata: Metadata = {
  title: "Tobacco Nepal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {/* <NavBar /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
